name: '🚀 Build and Publish jellyfin-ffmpeg'

on:
  release:
    types:
      - released

jobs:
  build_publish_debian:
    uses: ./.github/workflows/_meta.yaml
    with:
      distro: 'debian'
      codenames: '["bullseye", "bookworm", "trixie"]'
      architectures: '["amd64", "arm64"]'
      release: true

  build_publish_ubuntu:
    uses: ./.github/workflows/_meta.yaml
    with:
      distro: 'ubuntu'
      codenames: '["jammy", "noble"]'
      architectures: '["amd64", "arm64"]'
      release: true

  # Disabled as clang is stable.
  # build_publish_windows_portable:
  #   uses: ./.github/workflows/_meta_portable.yaml
  #   with:
  #     os: 'windows'
  #     architectures: '["win64"]'
  #     release: true
  #   secrets:
  #     deploy-host: ${{ secrets.REPO_HOST }}
  #     deploy-user: ${{ secrets.REPO_USER }}
  #     deploy-key: ${{ secrets.REPO_KEY }}

  build_publish_windows_clang_portable:
      uses: ./.github/workflows/_meta_win_clang_portable.yaml
      with:
        release: true

  build_publish_linux_portable:
    uses: ./.github/workflows/_meta_portable.yaml
    with:
      os: 'linux'
      architectures: '["amd64", "arm64"]'
      release: true

  build_publish_mac_portable:
      uses: ./.github/workflows/_meta_mac_portable.yaml
      with:
        release: true
